### ISSUE TITLE
Creating a Contributors tab

### ISSUE THREAD

**Issue by diya0603** [niharikaaa26/WolfTrack6.0#14]
need a contributors tab

**Comment by diya0603** [comment]
@all-contributors please add @Diya-Shetty for code

**Comment by diya0603** [comment]
@all-contributors please add @diya0603 for code

**Comment by niharikaaa26** [comment]
@all-contributors please add @nih326  @sanjana1399 @diya0603

**Comment by niharikaaa26** [comment]
@all-contributors please add @nih326 @sanjana1399 @diya0603 for code

**Comment by diya0603** [comment]
@all-contributors please add @nih326 for code
